---
title: "dataset ~ basic stats"
author: "2929porno"
date: "2021/12/05"
output: html_document
---

# データ整形

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
score <- read_csv("スコアボード.csv")
Manager <- read_csv("監督フォーメーション.csv")
score <- score %>%
  filter(rate != "") %>%   
  mutate(CP = ifelse(opponent_rate == "CP",1,0),　　　
         CP = as.factor(CP),
         opponent_rate = as.numeric(opponent_rate)) %>%
  mutate(called_game = ifelse(possesion == "C",1,0),
         possesion = as.numeric(possesion),
         pass = as.numeric(pass),
         shot = as.numeric(shot))

#resultの数値変換
score <- score %>% 
  mutate(W = str_detect(result,"勝"),
         D = str_detect(result,"引"),
         L = str_detect(result,"負"))
#Managerデータ追加
score_manager <- left_join(score, Manager,
                           by= "manager")
score <- score %>%
  filter(rate != "") %>%   
  mutate(CP = ifelse(opponent_rate == "CP",1,0),　　　
         CP = as.factor(CP),
         opponent_rate = as.numeric(opponent_rate)) %>%
  mutate(called_game = ifelse(possesion == "C",1,0),
         possesion = as.numeric(possesion),
         pass = as.numeric(pass),
         shot = as.numeric(shot))
```

```{r dataset, include=FALSE}

score %>% 
  group_by(manager) %>% 
  summarise(GF = mean(GF),
            GA = mean(GA),
            Win_rate = mean(W),
            lose_rate = mean(L),
            n = n(),
            rate = min(rate))

```
```{r dataset}
score <- score %>%
  filter(rate != "") %>%   
  mutate(CP = ifelse(opponent_rate == "CP",1,0),　　　
         CP = as.factor(CP),
         opponent_rate = as.numeric(opponent_rate)) %>%
  mutate(called_game = ifelse(possesion == "C",1,0),
         possesion = as.numeric(possesion),
         pass = as.numeric(pass),
         shot = as.numeric(shot))
#resultの数値変換
score <- score %>% 
  mutate(W = ifelse(result =="勝",1,0),
         D = ifelse(result =="引",1,0),
         L = ifelse(result =="負",1,0))　
#試合ごとのプレイヤーの得点の計算
Scorer <- score %>%
  select(-starts_with("assist"))%>%
  mutate(Messi = rowSums(.== "Messi", na.rm = T),
         Rummenigge = rowSums(.==  "Rummenigge", na.rm = T),
         Totti = rowSums(.== "Totti", na.rm = T),
         Cruijff = rowSums(.==  "Cruijff", na.rm = T),
         Beckham = rowSums(.==  "Beckham", na.rm = T),
         Ronaldinho = rowSums(.==  "Ronaldinho", na.rm = T),
         Ronaldo = rowSums(.==  "Ronaldo", na.rm = T),
         Jonathan = rowSums(.==  "Jonathan", na.rm = T),
         Isak = rowSums(.==  "Isak", na.rm = T),
         Law = rowSums(.==  "Law", na.rm = T),
         Vieira = rowSums(.==  "Vieira", na.rm = T),
         Rodrigo = rowSums(.==  "Rodrigo", na.rm = T),
         Nedved = rowSums(.==  "Nedved", na.rm = T),
         Nakata = rowSums(.==  "Nakata", na.rm = T),
         Havertz = rowSums(.== "Havertz", na.rm = T),
         Haaland = rowSums(.== "Haaland", na.rm = T),
         Boadu = rowSums(.== "Boadu", na.rm = T),
         vanBasten = rowSums(.== "van Basten", na.rm = T),
         Neymar = rowSums(.== "Neymar", na.rm = T))
#試合ごとのプレイヤーのアシストの計算
Assist <- score %>%
  select(-starts_with("score"))%>%
  mutate(Messi = rowSums(.== "Messi", na.rm = T),
         Rummenigge = rowSums(.==  "Rummenigge", na.rm = T),
         Totti = rowSums(.== "Totti", na.rm = T),
         Cruijff = rowSums(.==  "Cruijff", na.rm = T),
         Beckham = rowSums(.==  "Beckham", na.rm = T),
         Ronaldinho = rowSums(.==  "Ronaldinho", na.rm = T),
         Ronaldo = rowSums(.==  "Ronaldo", na.rm = T),
         Jonathan = rowSums(.==  "Jonathan", na.rm = T),
         Isak = rowSums(.==  "Isak", na.rm = T),
         Law = rowSums(.==  "Law", na.rm = T),
         Vieira = rowSums(.==  "Vieira", na.rm = T),
         Rodrigo = rowSums(.==  "Rodrigo", na.rm = T),
         Nedved = rowSums(.==  "Nedved", na.rm = T),
         Nakata = rowSums(.==  "Nakata", na.rm = T),
         Havertz = rowSums(.== "Havertz", na.rm = T),
         Haaland = rowSums(.== "Haaland", na.rm = T),
         Boadu = rowSums(.== "Boadu", na.rm = T),
         vanBasten = rowSums(.== "van Basten", na.rm = T),
         Neymar = rowSums(.== "Neymar", na.rm = T))
```


# 記述統計量

## オンラインマッチ対戦

```{r}
score %>% 
  filter(CP == 0) %>% 
  count()

```

## 選手ごとのゴール数（累計）

```{r}
goal_per_player <- Scorer %>%
  group_by(CP)%>%
  summarise(Messi = sum(Messi),
          Rummenigge = sum(Rummenigge),
          Totti = sum(Totti),
          Cruijff = sum(Cruijff),
          Beckham = sum(Beckham),
          Haaland = sum(Haaland),
          Ronaldo = sum(Ronaldo),
          Neymar = sum(Neymar),
          Isak = sum(Isak),
          Nakata = sum(Nakata),
          Vieira = sum(Vieira),
          Havertz = sum(Havertz),
          Boadu = sum(Boadu),
          vanBasten = sum(vanBasten))
goal_per_player %>%
  gather(key = player, value = goal, -CP) %>%
  filter(CP == 0,
         goal >= 3) %>% 
  ggplot(aes(reorder(player,-goal), goal, fill = goal ==max(goal)))+
  geom_bar(stat = "identity")+
  theme(axis.text.x = element_text(angle = 25, hjust = 1),
        legend.position = "none")+
  labs(x = "Player",title = "選手ごとの得点数", family = "Meiryo")+
  scale_fill_manual(values = c("grey", "#132B43"))


```

## 選手ごとのアシスト数（累計）

```{r}
Assist_per_player <- Assist %>%
  group_by(CP) %>%
  summarise(Messi = sum(Messi),
            Rummenigge = sum(Rummenigge),
            Totti = sum(Totti),
            Cruijff = sum(Cruijff),
            Beckham = sum(Beckham),
            Ronaldinho = sum(Ronaldinho),
            Ronaldo = sum(Ronaldo),
            Jonathan = sum(Jonathan),
            Isak = sum(Isak),
            Nakata = sum(Nakata),
            Vieira = sum(Vieira),
            Neymar = sum(Neymar),
            vanBasten = sum(vanBasten)) 
Assist_per_player %>%
  gather(key = player, value = Assist, -CP) %>%
  filter(CP==0,
         Assist >= 2)%>%
  ggplot(aes(x = reorder(player, -Assist), y = Assist, fill = 
               Assist==max(Assist)))+
  geom_bar(stat = "identity")+
  theme(axis.text.x = element_text(angle = 25, hjust = 1),
        legend.position = "none")+
  scale_y_continuous(breaks = seq(0,150, by = 2))+
  scale_fill_manual(values = c("grey", "#132B43"))+
  labs(x = "Player", title = "選手ごとのアシスト数",family = "Meiryo")

```

## 得点アシストが多い選手コンビ

```{r}
goals_assists <- score %>%
  mutate(avec = str_c(scorer,assist, sep = "_"),
         avec_1 = str_c(scorer_1,assist_1, sep = "_"),
         avec_2 = str_c(scorer_2,assist_2, sep = "_"),
         avec_3 = str_c(scorer_3,assist_3, sep = "_"),
         avec_4 = str_c(scorer_4,assist_4, sep = "_"),
         avec_5 = str_c(scorer_5,assist_5, sep = "_"),
         avec_6 = str_c(scorer_6,assist_6, sep = "_"),
         avec_7 = str_c(scorer_7,assist_7, sep = "_")) %>%
  gather(key = when_goal, value = avec_name,
         avec, avec_1, avec_2, avec_3, avec_4, avec_5, avec_6, avec_7) %>%
  select(date,id, when_goal, avec_name) %>%
  filter(date >= "2021-06-12") %>%
  count(avec_name) %>%
  arrange(desc(n)) %>%
  filter(!is.na(avec_name)) %>%
  filter(avec_name != "失点_ー")
goals_assists %>%
  filter(n >= 7) %>% 
  ggplot(aes(reorder(avec_name,-n),n))+
  geom_bar(stat = "identity")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  labs(x = "得点者_アシスト")
```

# フォーメーション分析

## 自陣フォーメーション

```{r}
score_manager %>% 
  filter(CP == 0) %>% 
  group_by(manager) %>% 
  summarise(n = n(),
            GF = mean(GF,na.rm = T),
            GA = mean(GA,na.rm = T),
            win = sum(W),
            shot = mean(shot,na.rm = T),
            pass = mean(pass,na.rm = T),
            Win_rate = mean(W),
            lose_rate = mean(L),
            possesion = mean(possesion,na.rm = T))

```

## レート推移（監督色分け）

```{r}
score_manager %>%
  filter(CP == 0) %>%
  ggplot(aes(x= 1:nrow(.), y= rate, color = factor(manager)))+
  geom_point()+
  geom_line()+
  labs(x = "試合数", y = "RATE", title  = "レート推移",
       family = "Meiryo", color = "manager")+
  scale_y_continuous(breaks = seq(1225, 1500, by = 10))+
  scale_x_continuous(breaks = seq(0, 200, by = 10))
```

## 相手フォーメーションごとの戦績

```{r}
#全戦績平均
score %>% 
  filter(CP == 0,
         manager %in% c(11)) %>% 
  summarise(GF = mean(GF),
            GA = mean(GA),
            Win_rate = mean(W),
            lose_rate = mean(L),
            n = n(),
            rate = min(rate)) %>% 
  filter(n >= 2)

#相手フォーメーションごと戦績
result_opsys <- score_manager %>% 
  filter(CP == 0,
         manager %in% c(11)) %>% 
  group_by(opponent_system) %>% 
  summarise(GF = mean(GF),
            GA = mean(GA),
            Win_rate = mean(W),
            lose_rate = mean(L),
            shot = mean(shot,na.rm = T),
            pass = mean(pass,na.rm = T),
            possesion = mean(possesion,na.rm = T),
            n = n(),
            rate = min(rate)) %>% 
  filter(n >= 2)

score_manager %>% 
  filter(CP == 0,
         manager == 11) %>% 
  ggplot()+
  geom_boxplot(aes(x = factor(opponent_system), y = shot))+
  geom_hline(yintercept = mean(score_manager$shot, na.rm = T))

#結果①
result_opsys
#結果②
#plot
result_opsys %>% 
  mutate(opponent_system = as.factor(opponent_system)) %>% 
  arrange(desc(opponent_system) )%>% 
  ggplot(aes(x = opponent_system, y = Win_rate,
             fill = Win_rate))+
  geom_hline(yintercept = 0.5, lty = 2, color = "#1b6401")+
  geom_bar(aes(y = Win_rate), stat = "identity")+
  geom_text(aes(label = round(Win_rate,3)), hjust = 1.4)+
  scale_fill_gradient2(low = "grey", high = "#64011b", aesthetics = "fill")+
  labs(y = "勝率", fill = "勝率")+
  coord_flip()+
  labs(title = "相手システムごとの戦績")


```
